version: 2
jobs:
  build:
    machine: true
    environment:
      FORK_URL: 'https://github.com/formio/formio'
      ORIG_URL: 'https://github.com/eole-repos/formio'
      DIR: 'formio'
    steps:
      - add_ssh_keys: 
          fingerprints:
                  - '49:f1:99:21:6f:6d:01:2a:6a:12:1a:59:7b:86:4e:51'
      - checkout
      - run: git clone $FORK_URL
        #- run: echo "git clone $FORK_URL"
      - run: cd  $DIR
        #- run: echo "cd  $DIR"
      - run: git remote add upstream $ORIG_URL
        #- run: echo "git remote add upstream $ORIG_URL"
      - run: git checkout master
      - run: git pull --no-edit upstream master
      - run: git push origin master
workflows: 
  version: 2
  cron_workflow: 
    triggers:
      - schedule:
          # UTC+0
          cron: "0 16 * * *"
          filters:
            branches:
              only: 
                - master
    jobs: 
      - build
  normal_workflow: 
     jobs: 
      - build

